-- 점수 사번 성명 직책 이메일
SELECT SUM(SCORE) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES NATURAL JOIN HR_GRADE
GROUP BY EMP_NO
HAVING SCORE = (
    SELECT MAX(SCORE) FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
        ) AS T
)
